export const screens = [
  {
    id: 'dashboard',
    num: 1,
    title: 'Tableau de bord',
    subtitle: 'Vue globale de l\'entreprise en temps réel',
    img: '/screenshots/03-dashboard.png',
    objective: 'Le tableau de bord centralise l\'ensemble des indicateurs clés de performance de l\'entreprise sur une seule interface. Il offre une vision synthétique et actualisée de l\'activité dès la connexion.',
    features: [
      'Indicateurs KPI dynamiques (employés, clients, projets, commandes)',
      'Chiffre d\'affaires consolidé et taux de complétion',
      'Répartition visuelle des projets (terminés / actifs / en attente)',
      'Générateur de rapport d\'audit intelligent',
      'Actions rapides pour la création d\'entités',
      'Flux d\'activité récente en temps réel',
    ],
    ai: 'L\'IA analyse les données pour calculer un Score de Santé de l\'Entreprise sur 100 points, détecte les déséquilibres et génère automatiquement des recommandations personnalisées.',
  },
  {
    id: 'login',
    num: 2,
    title: 'Connexion sécurisée',
    subtitle: 'Authentification moderne et fiable',
    img: '/screenshots/02-connexion.png',
    objective: 'L\'écran de connexion assure une authentification sécurisée des utilisateurs avec une interface épurée et professionnelle, conforme aux standards des applications SaaS.',
    features: [
      'Formulaire de connexion avec email et mot de passe',
      'Protection JWT via cookies httpOnly',
      'Messages d\'erreur explicites en français',
      'Redirection intelligente selon le rôle utilisateur',
      'Design responsive glassmorphism',
      'Pré-remplissage des identifiants de démonstration',
    ],
    ai: 'L\'IA surveille les tentatives de connexion suspectes et peut déclencher des alertes de sécurité automatiques via le système de notifications intelligentes.',
  },
  {
    id: 'hr',
    num: 3,
    title: 'Gestion des employés',
    subtitle: 'Module RH intelligent et complet',
    img: '/screenshots/04-rh.png',
    objective: 'Le module RH centralise la gestion du capital humain : consultation, recherche, filtrage et gestion complète des fiches employés avec suivi des présences et des congés.',
    features: [
      'Liste des employés avec fiches visuelles détaillées',
      'Recherche multicritères et filtres (département, statut)',
      'Formulaire complet d\'ajout et de modification',
      'Suivi des statuts : Actif, Congé, Inactif, Licencié',
      'Gestion des salaires, congés et compétences',
      'Statistiques RH agrégées',
    ],
    ai: 'L\'IA analyse les données RH pour suggérer des optimisations de productivité, détecter les déséquilibres de charge et recommander des répartitions de tâches intelligentes.',
  },
  {
    id: 'crm',
    num: 4,
    title: 'Gestion des ventes',
    subtitle: 'Suivi des commandes et analyse des revenus',
    img: '/screenshots/09-commandes.png',
    objective: 'Le module de ventes permet de suivre l\'intégralité du cycle commercial, de la commande à la livraison, avec une analyse automatique des revenus et des prévisions.',
    features: [
      'Tableau complet des commandes avec statuts visuels',
      'Filtres par statut et recherche textuelle',
      'Création de commandes avec articles dynamiques',
      'Calcul automatique des totaux et taxes',
      'Export CSV pour analyse externe',
      'Suivi du statut de paiement',
    ],
    ai: 'L\'IA génère des prévisions de revenus, identifie les tendances saisonnières et recommande des stratégies de pricing optimales basées sur l\'historique des ventes.',
  },
  {
    id: 'stock',
    num: 5,
    title: 'Gestion des stocks',
    subtitle: 'Inventaire intelligent et alertes automatiques',
    img: '/screenshots/08-stock.png',
    objective: 'Le module de stock offre une gestion complète des inventaires avec suivi en temps réel des produits, mouvements et alertes de réapprovisionnement.',
    features: [
      'Catalogue produits avec SKU, prix et catégories',
      'Historique des mouvements (entrées / sorties)',
      'Niveaux de stock avec barres de santé visuelles',
      'Alertes de stock faible (seuil minimum configurables)',
      'Trois vues : Produits, Mouvements, Niveaux de stock',
      'Recherche de produits',
    ],
    ai: 'L\'IA recommande les réapprovisionnements avant les ruptures, calcule les quantités optimales selon la vitesse d\'écoulement et priorise les alertes par impact business.',
  },
  {
    id: 'ai',
    num: 6,
    title: 'Assistant IA',
    subtitle: 'Chatbot intelligent et aide à la décision',
    img: '/screenshots/07-ia.png',
    objective: 'L\'assistant IA est le cœur intelligent de l\'application. Il permet d\'interagir avec les données en langage naturel, d\'automatiser des tâches et d\'obtenir des conseils stratégiques.',
    features: [
      'Chat conversationnel en langage naturel',
      'Actions rapides pour les requêtes courantes',
      'Questions suggérées pour guider l\'utilisateur',
      'Gestion des rappels intelligents avec priorités',
      'Historique complet des conversations',
      'Analyse des données de l\'entreprise en temps réel',
    ],
    ai: 'L\'assistant utilise un modèle d\'IA (Ollama / CodeLlama) pour comprendre le langage naturel, interroger la base de données, générer des rapports instantanés et fournir des conseils stratégiques personnalisés.',
  },
  {
    id: 'reports',
    num: 7,
    title: 'Rapports et audit',
    subtitle: 'Génération automatique et analyse prédictive',
    img: '/screenshots/13-audit.png',
    objective: 'Le module de rapports génère automatiquement des documents d\'audit complets avec analyse prédictive et recommandations stratégiques pour piloter l\'entreprise.',
    features: [
      'Génération de rapports d\'audit en un clic',
      'Score de santé globale de l\'entreprise',
      'Avertissements automatiques sur les anomalies',
      'Recommandations personnalisées par l\'IA',
      'Graphiques de performance et KPI',
      'Filtrage par période (semaine, mois, trimestre, année)',
    ],
    ai: 'L\'IA calcule un score de santé pondéré, détecte automatiquement les anomalies et déséquilibres, et génère des recommandations d\'action concrètes et contextualisées.',
  },
  {
    id: 'notifications',
    num: 8,
    title: 'Notifications intelligentes',
    subtitle: 'Alertes contextuelles et rappels automatiques',
    img: '/screenshots/03-dashboard.png',
    objective: 'Le système de notifications assure une communication proactive avec l\'utilisateur : alertes en temps réel, suggestions automatiques et rappels de tâches critiques.',
    features: [
      'Notifications en temps réel via WebSocket',
      'Rappels intelligents avec niveaux de priorité',
      'Types de rappels : Réunion, Deadline, Appel, Tâche',
      'Flux d\'activité récente consolidé',
      'Alertes système (base de données, API)',
      'Priorisation automatique des alertes',
    ],
    ai: 'L\'IA priorise les notifications selon leur urgence, suggère des rappels contextuels basés sur l\'analyse des données et détecte les inactions prolongées (ex : client non contacté depuis 30 jours).',
  },
  {
    id: 'settings',
    num: 9,
    title: 'Paramètres',
    subtitle: 'Profil, sécurité et préférences',
    img: '/screenshots/12-parametres.png',
    objective: 'L\'écran des paramètres centralise la configuration du compte utilisateur, la sécurité et les préférences personnelles pour une expérience sur mesure.',
    features: [
      'Gestion complète du profil utilisateur',
      'Paramètres de sécurité (mot de passe, session)',
      'Gestion des rôles et permissions',
      'Préférences d\'affichage et de notification',
      'Configuration multi-tenant (entreprise)',
      'Interface structurée par catégories',
    ],
    ai: 'L\'IA suggère des configurations optimales selon le profil d\'utilisation et recommande les permissions appropriées basées sur le rôle et les responsabilités de chaque utilisateur.',
  },
];

export const projectInfo = {
  name: 'SaaS Gestion d\'Entreprise',
  tagline: 'Powered by AI',
  students: ['Salaheddine Chouiref', 'Rida Akchach', 'Anas Gabbadi'],
  group: '4ISI',
  school: 'ISGA Fès',
  module: 'Entrepreneuriat',
  professor: 'Monsieur Alaoui',
  github: 'https://github.com/salahchouiref/saas_erp_fullapp',
  description: 'Plateforme SaaS intelligente de gestion d\'entreprise intégrant l\'intelligence artificielle pour l\'audit, les RH, la gestion des stocks, les commandes, la paie et l\'assistant virtuel.',
};
